/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.gui.comprobante;

import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;

import src.bankServer.regsYcomprobs.DatosComprobante;

/**
 *
 * @author Abeld
 */
public class Comprobante extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form compro
     */
    public Comprobante(DatosComprobante d) {
        datosConcepto.setText(d.concepto);
        datosCuentaDestino.setText(String.valueOf(d.cuentaDestino));
        datosFecha.setText(d.fecha.toString());
        datosMonto.setText(String.valueOf(d.monto));
        datosNumero.setText(String.valueOf(d.idComprobante));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPrincipal = new javax.swing.JPanel();
        Monto = new javax.swing.JLabel();
        datosFecha = new javax.swing.JLabel();
        datosCuentaDestino = new javax.swing.JLabel();
        datosConcepto = new javax.swing.JLabel();
        datosMonto = new javax.swing.JLabel();
        Comprobante = new javax.swing.JLabel();
        datosNumero = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        CuentaDestino = new javax.swing.JLabel();
        Concepto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(591, 444));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Monto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Monto.setForeground(new java.awt.Color(60, 63, 65));
        Monto.setText("Concepto:");

        Comprobante.setBackground(new java.awt.Color(0, 0, 0));
        Comprobante.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comprobante.setForeground(new java.awt.Color(60, 63, 65));
        Comprobante.setText("Comprobante de Transacción");

        Numero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Numero.setForeground(new java.awt.Color(60, 63, 65));
        Numero.setText("Fecha: ");

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(60, 63, 65));
        Fecha.setText("Cuenta De Destino: ");

        CuentaDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CuentaDestino.setForeground(new java.awt.Color(60, 63, 65));
        CuentaDestino.setText("Numero: ");

        Concepto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Concepto.setForeground(new java.awt.Color(60, 63, 65));
        Concepto.setText("Monto: ");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(panelPrincipalLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                                .addGroup(panelPrincipalLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(CuentaDestino,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Numero,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Monto,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Concepto,
                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGap(89, 89, 89)
                                                                .addGroup(panelPrincipalLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(datosFecha,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                299,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(datosCuentaDestino,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                299,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(datosConcepto,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                299,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(datosMonto,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                299,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(datosNumero,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                299,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(Fecha)))
                                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 303,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        panelPrincipalLayout.setVerticalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                panelPrincipalLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panelPrincipalLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
                                                        datosNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelPrincipalLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                        .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(
                                                                Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(126, 126, 126))
                                                .addGroup(panelPrincipalLayout.createSequentialGroup()
                                                        .addGroup(panelPrincipalLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        panelPrincipalLayout.createSequentialGroup()
                                                                                .addGroup(panelPrincipalLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(panelPrincipalLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        datosCuentaDestino,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        30,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(67, 67, 67))
                                                                                        .addComponent(
                                                                                                datosConcepto,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(datosMonto,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        30,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        panelPrincipalLayout.createSequentialGroup()
                                                                                .addComponent(datosFecha,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        30,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(175, 175, 175)))
                                                        .addGap(89, 89, 89)))));

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnGuardar)
                                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 415,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(155, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 306,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)
                                .addContainerGap(49, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try {

            PrinterJob job = PrinterJob.getPrinterJob();
            PageFormat pf = job.defaultPage();
            // pf.setOrientation(PageFormat.REVERSE_LANDSCAPE);
            job.setPrintable(this, pf);

            // Forma de la pagina
            // print and save the document
            this.btnGuardar.setVisible(false);
            job.print();
            this.btnGuardar.setVisible(true);
            // output done message

            System.out.println("Done!");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }// GEN-LAST:event_btnGuardarMouseClicked

    public int print(Graphics g, PageFormat pf, int pageIndex) {
        if (pageIndex == 0) {

            Graphics graphics = (Graphics) g;
            graphics.translate((int) pf.getImageableX(), (int) pf.getImageableY());

            printAll(graphics);

            return Printable.PAGE_EXISTS;
        } else {
            return Printable.NO_SUCH_PAGE;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comprobante;
    private javax.swing.JLabel Concepto;
    private javax.swing.JLabel CuentaDestino;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Monto;
    private javax.swing.JLabel Numero;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel datosConcepto;
    private javax.swing.JLabel datosCuentaDestino;
    private javax.swing.JLabel datosFecha;
    private javax.swing.JLabel datosMonto;
    private javax.swing.JLabel datosNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
