/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.formulario;

/**
 * @author Andres Moises
 */
public class formularioDeposito extends javax.swing.JFrame {

    /** Creates new form formularioDeposito */
    public formularioDeposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Monto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Formulario de Deposito");

        entrada.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        entradaActionPerformed(evt);
                    }
                });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGroup(
                                                layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .LEADING)
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addGap(172, 172, 172)
                                                                        .addComponent(jLabel2))
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addGap(125, 125, 125)
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                                javax
                                                                                                        .swing
                                                                                                        .GroupLayout
                                                                                                        .Alignment
                                                                                                        .LEADING)
                                                                                        .addComponent(
                                                                                                jLabel1)
                                                                                        .addGroup(
                                                                                                layout.createParallelGroup(
                                                                                                                javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout
                                                                                                                        .Alignment
                                                                                                                        .TRAILING,
                                                                                                                false)
                                                                                                        .addGroup(
                                                                                                                layout.createSequentialGroup()
                                                                                                                        .addComponent(
                                                                                                                                jButton1)
                                                                                                                        .addPreferredGap(
                                                                                                                                javax
                                                                                                                                        .swing
                                                                                                                                        .LayoutStyle
                                                                                                                                        .ComponentPlacement
                                                                                                                                        .RELATED,
                                                                                                                                javax
                                                                                                                                        .swing
                                                                                                                                        .GroupLayout
                                                                                                                                        .DEFAULT_SIZE,
                                                                                                                                Short
                                                                                                                                        .MAX_VALUE)
                                                                                                                        .addComponent(
                                                                                                                                jButton2))
                                                                                                        .addComponent(
                                                                                                                entrada,
                                                                                                                javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout
                                                                                                                        .PREFERRED_SIZE,
                                                                                                                356,
                                                                                                                javax
                                                                                                                        .swing
                                                                                                                        .GroupLayout
                                                                                                                        .PREFERRED_SIZE)))))
                                        .addContainerGap(119, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement
                                                        .UNRELATED)
                                        .addComponent(
                                                entrada,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(
                                                layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                        .BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                        .addContainerGap(58, Short.MAX_VALUE)));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void entradaActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    } // GEN-LAST:event_entradaActionPerformed

    private void jButton1ActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // TODO add your handling code here:
    } // GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    } // GEN-LAST:event_jButton2ActionPerformed

    static void MostrarFormulario() {}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioDeposito.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioDeposito.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioDeposito.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioDeposito.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
                    public void run() {
                        new formularioDeposito().setVisible(true);
                    }
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
